### ISSUE TITLE
Issue with XML package in Github r-lib v2 actions

### ISSUE THREAD

**Issue by maelle** [eblondel/ows4R#71]
Related to #59 

Just for info we're seeing such compilation errors on Ubuntu with XML: [EMODnet/EMODnetWFS/runs/6176000380?check_suite_focus=true](https://github.com/EMODnet/EMODnetWFS/runs/6176000380?check_suite_focus=true)

Cc @annakrystalli

**Comment by eblondel** [comment]
it's not really related to #59 by the way :-)

**Comment by eblondel** [comment]
@maelle i've configured the github CI with ubuntu-latest for both R release/devel, and it works. Not sure why you got a compilation issue, maybe it's unexpected error, and trying to re-run the job will work.

**Comment by maelle** [comment]
Thanks, will do!

**Comment by maelle** [comment]
@eblondel do you know of examples of GHA workflow without Docker that'd work for XML? Our standard workflows still don't work (which worries me for standard users that will try to install the package outside of Docker too). See https://github.com/EMODnet/EMODnetWFS/actions/runs/2257266720

Thank you :pray:

**Comment by eblondel** [comment]
@maelle just a clarification, I'm not containerizing the tests within docker, but Docker is used to launch some applications WITHIN the VM that is launched with ubuntu for tests. Most of the packages i authored used XML behind, such as [geometa](https://github.com/eblondel/geometa), [geosapi](https://github.com/eblondel/geosapi), [atom4R](https://github.com/eblondel/atom4R). I'm going to add more configs to them to test them deeply, and to have a look to your config above to see what you could do.

**Comment by eblondel** [comment]
@maelle looking at your action config, I see that you use v2 actions from r-lib, while in ows4R I used 'v1' for r-setup and r-setup-dependencies; and 'check-r-package' for check-r-package action https://github.com/eblondel/ows4R/blob/master/.github/workflows/r-cmd-check.yml#L46
This may be related in particular to https://github.com/r-lib/actions/tree/v2-branch/setup-r-dependencies#installing-the-latest-dependencies I'm going to give a try over v2 r-lib/actions with ows4R and let you know

**Comment by eblondel** [comment]
reverting at https://github.com/eblondel/ows4R/commit/6eac34136f29a2677f2ea707bff39cd05b8ab8db

**Comment by eblondel** [comment]
@maelle this is what I could investigate related to Github CI failures in building XML package:
*  first, i've tried to switch from v1 to v2 actions, and this is how I could reproduce the issue of Github action r-lib/actions/setup-r-dependencies@v2 same as you are facing in https://github.com/EMODnet/EMODnetWFS 
* As pointed out the issue relates to this https://github.com/r-lib/actions/tree/v2-branch/setup-r-dependencies#installing-the-latest-dependencies, and the fact that in your build a cached version of the XML package is taken (3.99-0.3) instead of the latest XML version (see https://github.com/EMODnet/EMODnetWFS/runs/6347468114?check_suite_focus=true#step:5:5586)
* To fix the issue, I've enabled v2 action again, but paying attention to add 'XML' package as extra-packages (see https://github.com/eblondel/ows4R/blob/master/.github/workflows/r-cmd-check.yml#L54) to make sure to download the latest version from CRAN. With this the build goes well on _ubuntu-latest_ for both R _release_ and _devel_

Let me know if this fixes your build for https://github.com/EMODnet/EMODnetWFS

**Comment by maelle** [comment]
Success https://github.com/EMODnet/EMODnetWFS/runs/6521287978?check_suite_focus=true :tada: 

Thank you!!
